# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ef0fU0K3nbmX8nx88-3nXu8PyjwN4_s
"""

import streamlit as st
import zipfile
import io
import random
import requests
import unicodedata
import re

def generate_hint(answer: str) -> str:
    if not answer:
        return ""
    first = answer[0]
    masked = ""
    for char in answer[1:]:
        if char.isalpha() or ('ぁ' <= char <= 'ん') or ('ァ' <= char <= 'ン') or ('一' <= char <= '龥'):
            masked += "〇"
        elif char == " ":
            masked += "□"
        else:
            masked += char
    return f"{first}{masked}（全{len(answer)}文字）"

def normalize(text: str) -> str:
    return unicodedata.normalize("NFKC", text).lower().replace(" ", "").replace("　", "")

def extract_answer(filename: str) -> str:
    name = filename.rsplit("/", 1)[-1].rsplit(".", 1)[0]
    parts = name.split("_", 1)
    return parts[1] if len(parts) == 2 else parts[0]

def init_session():
    defaults = {
        "questions": [],
        "current_q": 0,
        "score": 0,
        "zip_data": None,
        "played": False,
        "answered": False,
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val

init_session()

st.title("🎮 インターネット検定楽曲編（Dropboxリンク式）")
st.markdown("""
#### 📝 説明
- 曲の一部が流れます。
- **