# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ef0fU0K3nbmX8nx88-3nXu8PyjwN4_s
"""

import streamlit as st
import zipfile
import io
import random
import requests
import unicodedata
import re

# ヒント生成関数（最初の1文字＋〇＋文字数表示）
def generate_hint(answer: str) -> str:
    if not answer:
        return ""
    first = answer[0]
    masked = ""
    for char in answer[1:]:
        if char.isalpha() or ('ぁ' <= char <= 'ん') or ('ァ' <= char <= 'ン') or ('一' <= char <= '龥'):
            masked += "〇"
        elif char == " ":
            masked += "□"
        else:
            masked += char
    return f"{first}{masked}（全{len(answer)}文字）"

# 正規化（全角→半角、小文字化、空白除去）
def normalize(text: str) -> str:
    return unicodedata.normalize("NFKC", text).lower().replace(" ", "").replace("　", "")

# ファイル名から答えを抽出
def extract_answer(filename: str) -> str:
    name = filename.rsplit("/", 1)[-1].rsplit(".", 1)[0]
    parts = name.split("_", 1)
    return parts[1] if len(parts) == 2 else parts[0]

# ファイル名から難易度を抽出（☆なし→☆2扱い）
def extract_difficulty(filename: str) -> str:
    match = re.search(r'☆[1-5]', filename)
    return match.group() if match else "☆2"

# 出題インデックスからゾーン判定
def get_zone(index: int) -> str:
    if index < 5:
        return "☆1"
    elif index < 20:
        return "☆2"
    elif index < 30:
        return "☆3"
    elif index < 40:
        return "☆4"
    else:
        return "☆5"

# セッション初期化
def init_session():
    defaults = {
        "questions": [],
        "current_q": 0,
        "score": 0,
        "zip_data": None,
        "played": False,
        "answered": False,
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val

init_session()

# タイトルと説明
st.title("🎮 インターネット検定楽曲編（Dropboxリンク式）")
st.markdown("""
#### 📝 説明
- 曲の一部が流れます。
- **ひらがな、アルファベットの小文字**で回答してください。
- **スペース（□）、ドット、記号**はヒントとして表示されます。ヒントも入力してください。
- 200問以上の中から**50問までランダム出題**されます。
- 問題は**一度しか流れません**。
- 出題基準は「**インターネットを見ていれば回答できる**」です。
- 音量が一定でないので、**音量の上げすぎにはご注意ください**。
- https://www.dropbox.com/scl/fi/i50xzf0isskjrle7yrcof/mp3-10.zip?rlkey=7ke725jn53j7qb0k6cfiptvtx&st=4uv4cp2y&raw=1

""")

# Dropboxリンク入力欄
dropbox_url = st.text_input("📎 DropboxのZIPファイルリンクを入力（末尾は ?raw=1 にしてください）")

# 初回ロード時にZIPを読み込む
if dropbox_url and not st.session_state.questions:
    with st.spinner("ZIPファイルをダウンロード中..."):
        response = requests.get(dropbox_url)
        st.session_state.zip_data = io.BytesIO(response.content)

        with zipfile.ZipFile(st.session_state.zip_data) as z:
            all_mp3 = [f for f in z.namelist() if f.endswith(".mp3")]

            # 難易度別に分類（☆なし→☆2）
            difficulty_groups = {"☆1": [], "☆2": [], "☆3": [], "☆4": [], "☆5": []}
            for f in all_mp3:
                diff = extract_difficulty(f)
                ans = extract_answer(f).strip()
                if diff in difficulty_groups:
                    difficulty_groups[diff].append({"file": f, "answer": ans})

            # 出題順に応じてゾーンから抽選（重複なし）
            selected_questions = []
            used_files = set()
            for i in range(50):
                zone = get_zone(i)
                pool = [q for q in difficulty_groups.get(zone, []) if q["file"] not in used_files]
                if pool:
                    q = random.choice(pool)
                    selected_questions.append(q)
                    used_files.add(q["file"])

            st.session_state.questions = selected_questions

# クイズ進行
if st.session_state.questions:
    idx = st.session_state.current_q

    if idx >= len(st.session_state.questions):
        st.markdown("---")
        st.header("🏁 クイズ終了！")
        st.write(f"あなたのスコア：**{st.session_state.score} / {len(st.session_state.questions)}**")
        st.balloons()
        for key in ["questions", "current_q", "score", "zip_data", "played", "answered"]:
            st.session_state[key] = {
                "questions": [],
                "current_q": 0,
                "score": 0,
                "zip_data": None,
                "played": False,
                "answered": False,
            }[key]
        st.stop()

    q = st.session_state.questions[idx]
    difficulty = extract_difficulty(q["file"])

    with zipfile.ZipFile(st.session_state.zip_data) as z:
        if not st.session_state.played:
            st.audio(z.read(q["file"]), format="audio/mp3")
            st.session_state.played = True

    st.subheader(f"🎵 第 {idx + 1} 問（難易度：{difficulty}）")
    st.write("🔍 ヒント：" + generate_hint(q["answer"]))

    user_input = st.text_input("答えを入力（ひらがな・英小文字）", key=f"answer_{idx}")

    if not st.session_state.answered and st.button("回答する"):
        st.session_state.answered = True
        if normalize(user_input) == normalize(q["answer"]):
            st.success("🎉 正解！")
            st.session_state.score += 1
        else:
            st.error(f"❌ 不正解… 正解は「{q['answer']}」でした")

    if st.session_state.answered:
        if st.button("次の問題へ"):
            st.session_state.current_q += 1
            st.session_state.played = False
            st.session_state.answered = False